### ISSUE TITLE
有关Flicker和NUSWild数据集超参的问询。

### ISSUE THREAD

**Issue by diaoyudiaochan** [kalenforn/DCHMT#4]
作者您好，感谢您愿意共享这篇发表在MM上的论文代码。我在follow您github主页上给出的步骤复现论文结果的时候遇到了一个问题，特来请教。
1. 当我直接用您给的运行coco数据集的命令去跑flicker数据集时（python main.py --is-train --hash-layer select --dataset flicker25k --caption-file caption.mat --index-file index.mat --label-file label.mat --similarity-function euclidean --loss-type l2 --vartheta 0.75 --lr 0.0001 --output-dim 64 --save-dir ./result/flicker25k/64 --clip-path ./ViT-B-32.pt --batch-size 256），loss不收敛，猜测是每个数据集应设置不同的超参，因此想问下您flicker和nuswild数据集的超参设置是什么呀？
2. 论文中您说所有的实验都在一块GV100上实现，请问可否告知一下在各个数据集上训练和推理所用的时间？
期待您的回复，祝您生活愉快！

**Comment by kalenforn** [comment]
Thanks for your follow! 
I remember that this model is faster than coco when running on the flickr25k, it takes above six hours of training. The parameters I set are the same as coco, but only the "--vartheta" is different, how to set "--vartheta" has been explained in my experiments. I think the problem of no-convergence may be your dataset error, please check your dataset-making process.
For the inferencing process, I haven't tested because the testing data is a random choice from the whole dataset and I haven't written the saving code.
